version: "3.7"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: abacaxi
      POSTGRES_DB: carros
    ports: 
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    image: node
    ports:
      - 3000:3000
    volumes: 
      - ./:/app
    working_dir: /app
    command: ["yarn", "dev"]
  adminer:
    image: adminer
    ports: 
      - 8080:8080
    

volumes: 
  db:
  